### ISSUE TITLE
Is it possible to make pydbg work with namedtuples?

### ISSUE THREAD

**Issue by 1081** [tylerwince/pydbg#13]
```python

from collections import namedtuple
import pydbg as dbg

Car = namedtuple('Car', ['color', 'mileage',])

my_car = Car('red', 3812.4)

print(my_car.color)
dbg(my_car.mileage)
```

TypeError: 'module' object is not callable

**Comment by tylerwince** [comment]
Hi @1081 -- `pydbg` will work with all objects which have a `__repr__` method (NamedTuples) do have this. It looks like you need to change your import statement to `from pydbg import dbg` -- this is the cause of the error you are seeing. 

Let me know if you still see this after changing your import statement, happy to help. Thanks for using pydbg!
