### ISSUE TITLE
Note that Python 3.8 f-strings has support for something very similar 

### ISSUE THREAD

**Issue by nealmcb** [tylerwince/pydbg#16]
See [What’s New In Python 3\.8: f-strings support = for self-documenting expressions and debugging](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging)

```
>>> print(f'{theta=}  {cos(radians(theta))=:.3f}')
theta=30  cos(radians(theta))=0.866
```

Yay for Python!

Much less need for `pydbg` in Python 3.8+ now.

Sorry I didn't run across pydbg when it came out!

Thanks for all the fish!

**Comment by tylerwince** [comment]
Yep! 3.8 now supports very similar functionality. I would recommend using that if you are able to use 3.8 and only use pydbg if you are forced to stay on 3.7 or earlier.

Thanks for the callout @nealmcb
