### ISSUE TITLE
Compare with q?

### ISSUE THREAD

**Issue by anntzer** [tylerwince/pydbg#6]
It's nice to see a new project on this front.
Perhaps you may want to compare the feature set with https://pypi.org/project/q/, which has served me very well (and still does), but is in a semi-unmaintained state right now.
A few things that I see:
- q(...) returns the value of the debugged expression, so that one can embed it in the middle of an expression -- looks like rust's dbg does too? (One can also use e.g. `q|foo` or `q/foo` if typing the closing parenthesis is too hard, but I think reasoning about operator precedence is just not worth it.)
- q does some magic so that the q module itself is the debugging object, i.e. one can do `import q; q("foo")` -- a bit magic, but much shorter than `from pydbg import dbg; ...`
- q prints its (colorized) output to /tmp/q which avoids interlacing with actual program output -- at least this would be nice as an option.
- q also works as a function decorator, printing function args and return value.
- (q.d() is a synonym for breakpoint(), which isn't too much of a big deal now that breakpoint() is a builtin anyways.)

**Comment by tylerwince** [comment]
I am going to close this issue so we can save it for posterity but there isn't anything actionable. Thanks for the link to another project!
